# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: Test Product

    jobs:
      - template: azure-pipelines-test.yml
        parameters:
          images: ['ubuntu-latest', 'macOS-latest' ] #, 'vs2017-win2016' ]
          pythonVersions: [ '3.8' ]

  - stage: Build
    displayName: Build and push docker image
    dependsOn: []
    jobs:
      - job: buildAndPushDockerImage
        pool:
          name: Azure Pipelines
          vmImage: 'ubuntu-latest'

        steps:
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Azure Container Registry'
          inputs:
            azureSubscription: 'flask-tdd-docker - Azure'
            resourceGroupName: 'flask-tdd-docker-solarmist-test'
            location: 'South Central US'
            templateLocation: 'URL of the file'
            csmFileLink: 'https://raw.githubusercontent.com/Microsoft/devops-project-samples/057f6cc268a62922d012067d069d58684e967d0a/armtemplates/webapp-containers/containerRegistry-template.json'
            overrideParameters: '-registryName "flaskTddDocker" -registryLocation "West US" -registrySku "Basic"'

        - task: Docker@1
          displayName: 'Build an image'
          inputs:
            azureSubscriptionEndpoint: 'flask-tdd-docker - Azure'
            azureContainerRegistry: flasktdddocker.azurecr.io
            dockerFile: '**/Dockerfile.prod'
            imageName: 'flasktdddocker:$(Build.BuildId)'

        - task: Docker@1
          displayName: 'Push an image'
          inputs:
            azureSubscriptionEndpoint: 'flask-tdd-docker - Azure'
            azureContainerRegistry: flasktdddocker.azurecr.io
            command: 'Push an image'
            imageName: 'flasktdddocker:$(Build.BuildId)'

