# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: Test Product

    jobs:
      - template: azure-pipelines-test.yml
        parameters:
          images: ['ubuntu-16.04', 'macOS-latest', 'vs2017-win2016' ]
          pythonVersions: [ '3.6', '3.7', '3.8' ]


  - stage: Build
    displayName: Build image
    dependsOn: []
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile.prod'
          tags: |
            $(tag)