# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: Test Product

    jobs:
      - template: azure-pipelines-test.yml
        parameters:
          images: ['ubuntu-latest', 'macOS-latest' ] #, 'vs2017-win2016' ]
          pythonVersions: [ '3.8' ]


  - stage: Build
    displayName: Build and push stage
    dependsOn: []
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile.prod'
          containerRegistry: 'Docker Container Registry'
          repository: flask-tdd-docker
          tags: |
            $(tag)