# Docker compose file version
version: '3.7'

services:

    users:  # Service called "users"
        build:
            context: .  # The path containing the Dockerfile or a URL to a git repo
            dockerfile: Dockerfile
        entrypoint: ["/usr/src/app/entrypoint.sh"]
        volumes:
            - ./:/usr/src/app
            # This is used to mount the code from the current dir into the container. Needed for dev otherwise you'd need to rebuild the image for every change.
        ports:
            - 5001:5000
        env_file:
            - ./.env.common
            - ./.env.dev
        depends_on:
            - users-db

    users-db:
        build:
            context: ./project/db
            dockerfile: Dockerfile
        expose:
            - 5432
        env_file:
            - ./.env.dev